server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ruta-canchas
          uri: http://ms-canchas:8081
          predicates:
            - Path=/canchas/**
        - id: ruta-equipamiento
          uri: http://ms-equipamiento:8082
          predicates:
            - Path=/equipamiento/**
        - id: ruta-usuarios
          uri: http://ms-usuarios:8083
          predicates:
            - Path=/usuarios/**
        - id: ruta-reservas
          uri: http://ms-reservas:8084
          predicates:
            - Path=/reservas/**
        - id: ruta-pagos
          uri: http://ms-pagos:8085
          predicates:
            - Path=/pagos/**