server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-canchas
          uri: lb://ms-canchas
          predicates:
            - Path=/canchas/**
            
        - id: ms-equipamiento
          uri: lb://ms-equipamiento
          predicates:
            - Path=/equipamiento/**
            
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/usuarios/**
            
        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/reservas/**
            
        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/pagos/**
            
        - id: ms-autenticacion
          uri: lb://ms-autenticacion
          predicates:
            - Path=/auth/**
            
        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/notificaciones/**
            
        - id: ms-fairplay
          uri: lb://ms-fairplay
          predicates:
            - Path=/fairplay/**
            
        - id: ms-resenas
          uri: lb://ms-resenas
          predicates:
            - Path=/resenas/**
            
        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/reportes/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/